services:
  - type: web
    name: plms-dashboard
    env: node
    region: singapore
    plan: free
    buildCommand: npm install --prefix backend && npm install --prefix frontend && npm run build --prefix frontend
    startCommand: node backend/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://aqms_user:EwazH8Iks5Hb2EjRDC4rlFeOWkNUBpXQ@dpg-d74l6ne3jp1c7395i7o0-a.singapore-postgres.render.com/aqms
      - key: PORT
        value: 10000
      - key: HIVEMQ_URL
        value: mqtt://broker.hivemq.com:1883
      - key: JWT_SECRET
        value: change_this_to_a_long_random_secret_in_production
      - key: SMTP_USER
        value: kassandra.glover@ethereal.email
      - key: SMTP_PASS
        value: 6yC19B4C3g6SZNXStH
